Update files to actually reflect 2.9.5 version
There is an issue while using virt-manager with libxml2-python3
installed by pip:

Traceback (most recent call last):
  File "/usr/share/virt-manager/virtManager/details.py", line 1857, in remove_device
    self.vm.remove_device(devobj)
  File "/usr/share/virt-manager/virtManager/domain.py", line 452, in remove_device
    xmlobj.remove_device(editdev)
  File "/usr/share/virt-manager/virtinst/guest.py", line 438, in remove_device
    self.devices.remove_child(dev)
  File "/usr/share/virt-manager/virtinst/xmlbuilder.py", line 709, in remove_child
    self._xmlstate.xmlapi.node_force_remove(xpath)
  File "/usr/share/virt-manager/virtinst/xmlapi.py", line 174, in node_force_remove
    self._node_remove_child(parentnode, childnode)
  File "/usr/share/virt-manager/virtinst/xmlapi.py", line 375, in _node_remove_child
    if all([node_is_text(n) for n in parentnode.children]):
TypeError: iter() returned non-iterator of type 'xmlCoreDepthFirstItertor'

The error is caused by missing __next__ method in that Class and it's
because the libxml2.py file is for some reason different then the
libxml.py file.

Signed-off-by: Pavel Hrdina <phrdina@redhat.com>